# Generated by Django 3.1.6 on 2021-02-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210220_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, default='https://gitcdn.link/repo/SammanthaPS/Images/main/noimage.png', max_length=200),
        ),
    ]
