# Generated by Django 3.1.6 on 2021-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Enter a title for the auction.', max_length=25),
        ),
    ]
